Model deployment
AI4HF/passport pull request #12
Opened 2024-07-22 10:28 UTC by oburakcinar

2024-07-22 11:18 UTC, Okanmercan99 requested changes

2024-07-22 11:18 UTC, Okanmercan99 commented on src/main/java/io/passport/server/service/ModelDeploymentService.java
> +        LocalDateTime now = LocalDateTime.now();
Let's use Instant class for time class. Please update all time class usages accordingly.

2024-07-22 11:18 UTC, Okanmercan99 commented on src/main/java/io/passport/server/service/ModelDeploymentService.java
> +            Optional.ofNullable(updatedModelDeployment.getModelId()).ifPresent(modelDeployment::setModelId);
Let's simplfy there as other service classes. We do not need silent null checking like this.

2024-07-22 13:11 UTC, Okanmercan99 requested changes

2024-07-22 13:11 UTC, Okanmercan99 commented on src/main/java/io/passport/server/model/ModelDeployment.java
> +    private Timestamp createdAt;
Let's use instant objects here and all similiar usages also.

2024-07-22 13:11 UTC, Okanmercan99 commented on src/main/java/io/passport/server/service/ModelDeploymentService.java
> +            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss").withZone(ZoneId.systemDefault());
You do not need to format time. You can pass Instant object directly to database.

2024-07-22 13:29 UTC, Okanmercan99 approved these changes

2024-07-23 12:29 UTC, dogukan10 commented on src/main/resources/application.properties
> +keycloak.credentials.secret=i9Gm2CbhusqLUGmamK25yvo9ZHf69QIj
Please revert this change back. You can change it in your local while developing the code.

2024-07-23 12:51 UTC, merged