Model, Deployment and Passport Management Modules
AI4HF/passport pull request #18
Opened 2024-08-05 10:08 UTC by KeremHmd

Three new modules are implemented on top of all the other required changes to the existing tools.

2024-08-06 07:41 UTC, Okanmercan99 requested changes

2024-08-06 07:41 UTC, Okanmercan99 commented on src/main/java/io/passport/server/controller/ModelDeploymentController.java
> +    @GetMapping("/environment/{environmentId}")
Let's query by RequestParam, not PathVariable for API convenience.

2024-08-06 07:41 UTC, Okanmercan99 commented on src/main/java/io/passport/server/repository/PassportRepository.java
> +public interface PassportRepository extends JpaRepository<Passport, Long> {
Missing comment.

2024-08-06 07:41 UTC, Okanmercan99 commented on src/main/java/io/passport/server/service/DeploymentEnvironmentService.java
> +     * @param deploymentEnvironmentId ID of the personnel
Let's corrrect comment here.

2024-08-07 07:09 UTC, Okanmercan99 approved these changes

2024-08-07 13:22 UTC, dogukan10 approved these changes

2024-08-07 13:24 UTC, merged