Multiple Role Authorization
AI4HF/passport pull request #23
Opened 2024-12-04 12:15 UTC by KeremHmd

- Study-Based Authorization Integration with Keycloak Groups
- Role-Based Authorization Updates
- ML_ENGINEER Introduction to the System
- Dependency and System Version Updates

2024-12-18 13:03 UTC, Okanmercan99 requested changes

2024-12-20 07:16 UTC, KeremHmd commented on src/main/java/io/passport/server/repository/StudyPersonnelRepository.java
> +    List<StudyPersonnel> findStudyPersonnelById_PersonnelId(String personId);
Repository only accepts the current method name without in-depth changes to Study Personnel entity.

2025-01-02 10:14 UTC, dogukan10 commented on pom.xml
> +                    <source>16</source>
This project is configured to use Java 16 or Java 21 ? The current configuration contradicts the `<java.version>21</java.version>` setting.

2025-01-30 13:36 UTC, Okanmercan99 approved these changes

2025-01-30 13:37 UTC, merged